_format_version: "3.0"
_transform: true

services:
  - name: orders
    protocol: http
    host: host.docker.internal
    port: 3333
    routes:
      - name: api
        protocols:
          - http
          - https
        paths:
          - /orders

  - name: invoices
    protocol: http
    host: host.docker.internal
    port: 3333
    path: /
    routes:
      - name: api-invoices
        protocols:
          - http
          - https
        paths:
          - /invoices


        plugins:
          - name: cors
            config:
              origins:
                - "*"
              methods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              headers:
                - Accept
                - Content-Type
                - Authorization
